#Docker image from Docker Hub
image: mikk3lro/docker-phpunit-php7:7.2-phpunit6

#Minutes:
max-time: 2

pipelines:
  #Executes on every push that do not match other rules
  default:
    - step:
        caches:
          - composer
        script:
          - composer --no-interaction install
          - vendor/bin/phpunit
          - chmod +x increment_version.sh && ./increment_version.sh
          - curl -s https://mikk3lro.bitbucket.io/push_version.sh | sh